version: 2.1

orbs:
  cypress: cypress-io/cypress@1.29.0
  slack: circleci/slack@4.10.1

executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
workflows:
  version: 2
  test:
    jobs:
      - cypress/run:
          executor: with-chrome
          browser: chrome
          context: slack-context
          post-steps:
            - slack/notify:
                event: fail
                template: basic_fail_1
